name: canonicalizer
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - ipywidgets
  - pip
  - pip:
    - accelerate
    - dedent
    - bitsandbytes
    - langchain-neo4j
    - langchain
    - langchain-core
    - langchain-ollama
    - langchain-openai
    - langchain-experimental
    - langgraph
    - langsmith
    - rapidfuzz
    - sentence-transformers
    - sentencepiece
    - semchunk
    - scikit-learn
    - tiktoken
    - pandas
    - python-dotenv
    - plotly
    - protobuf
    - matplotlib
    - seaborn
    - rerankers
    - requests
    - datasets
    - pywikibot
    - pytest
    - joblib
